public enum GameEvent
{
    None,
    OnPlayerFired,
    OnAsteroidDestroyed,
    OnPlayerDamaged,
    PlayerShipDestroyed,
    OnUnlockAchievement,
    OnNextLevel,
    OnActiveSkill,
    EarnCoin,
    Pause,
    OnEnemyDamaged,
    FightBoss,
    OnDestroyedMiniBoss,
    OnDestroyedSuperBoss,
    OnDestroyedEnemy,
    OnChangeBattleWorld,
    OnLoadMainScene
}